version: "3.9" # optional since v1.27.0
services:
  go:
    build: ./go
    stop_signal: SIGINT
    ports:
      - "8081:8080"
    volumes:
      - ./stats/go:/app/stats
  java:
    build: ./java
    stop_signal: SIGINT
    ports:
      - "8082:8080"
    volumes:
      - ./stats/java:/app/stats
  node:
    build: ./node
    stop_signal: SIGINT
    ports:
      - "8083:8080"
    volumes:
      - ./stats/node:/usr/src/app/stats
  php:
    build: ./php
    stop_signal: SIGINT
    ports:
      - "8084:80"
    volumes:
      - ./stats/php:/var/www/html/stats
  python:
    build: ./python
    stop_signal: SIGINT
    ports:
      - "8085:8080"
    volumes:
      - ./stats/python:/app/stats
