version: "3.9" # optional since v1.27.0
services:
  go:
    build: ./go
    ports:
      - "8081:8080"
  java:
    build: ./java
    ports:
      - "8082:8080"
  node:
    build: ./node
    ports:
      - "8083:8080"
  php:
    build: ./php
    ports:
      - "8084:80"
  python:
    build: ./python
    ports:
      - "8085:8080"
